# Лабораторная работа 5. Структурированные типы данных

# Домашнее задание (базовое):

# Задание 1.

С клавиатуры вводится строка, включающая строчные и прописные буквы. Требуется вывести ту же строку в изменённом регистре, тип регистра зависит от того, каких букв больше. При равном количестве букв в заглавном и проптсном регистре - выводится оригинальная строка. 

Например, вводится строка "HeLLo World", она должна быть преобразована в "hello world", потому что в исходной строке малых букв больше. 

В программе можно использовать строковые методы: upper() (преобразование к верхнему регистру) и lower() (преобразование к нижнему регистру), isupper() и islower() (проверяющие регистр строки или символа).

In [ ]:
#s = input("Input the string: ")
s = 'tr56t'
count_supper = 0
count_lower = 0
for i in s:
  if i.isupper() == True:
    count_supper = count_supper + 1
  else:
    count_lower = count_lower + 1

if count_supper != count_lower :
  s =  s.upper() if count_supper > count_lower else s.lower()
print(s)

tr56t


# Задание 2

Дано слово "объектно-ориентированный". Используя индексацию и срезы составьте из него как можно больше слов "объект", "ориентир", "тир", "кот", "рента" и тд. Выведите их на экран.

In [ ]:
s =  "объектно-ориентированный"
'''Всевозможные комбинации из 2 и 3 букв, не являющиеся бредом (всевозможные реальные слова из слова s). Вместо этого также подошел бы русский словарь'''
Russian_dictionary = ('аи', 'ар', 'ат', 'ер', 'ир', 'ни', 'но', 'он', 'ор', 'ра', 'ре', 'ро', 'та',
                      'аир', 'акр', 'акт', 'ант', 'арк', 'бак', 'бар', 'бат', 'бек', 'бит', 'боа', 
                      'бок', 'бон', 'бор', 'бот', 'бра', 'бык', 'быт', 'вак', 'вар', 'век', 'вир', 'вор', 'ева',
                      'ера', 'еры', 'ива', 'икт', 'инк', 'ион', 'кан', 'кар', 'кат', 'кеб', 'кен', 'кин', 'кит', 
                      'ков', 'кон', 'кот', 'нар', 'нет', 'нит', 'нок','нтв', 'обр', 'око', 'она', 'оон', 'орт', 
                      'раб', 'рак', 'рев', 'ров', 'рок', 'рот', 'рык', 'тат', 'тек', 'тик', 'тир', 'ток', 'тон', 'тор', 'тот', 'три', 'тын')
words = set()
for j  in range(0,len(s)):
  for z in  range(0,len(s)):
    word = s[j]+s[z]
    if word in Russian_dictionary:
      words.add(word)

for i in range(0,len(s)):
  for j  in range(0,len(s)):
    for z in  range(0,len(s)):
      word = s[i]+s[j]+s[z]
      if word in Russian_dictionary:
        words.add(word)

# и т.д.
# for i in range(0,len(s)):
#   for j  in range(0,len(s)):
#     for z in  range(0,len(s)):
#       for k in range(0,len(s)):
#         word = s[i]+s[j]+s[z] + s[k]
#         if word in Russian_dictionary:
#            words.add(word))
#...

""" и так далее по количеству бекв в слове s"""

print(len(Russian_dictionary), len(words), '=> количество слов совпало!')
print(words)

80 80 => количество слов совпало!
{'кан', 'кот', 'вор', 'бак', 'тир', 'тын', 'рык', 'но', 'аир', 'бор', 'ра', 'арк', 'акр', 'ров', 'оон', 'аи', 'ион', 'рак', 'вак', 'акт', 'ар', 'икт', 'ор', 'кит', 'ков', 'бек', 'бык', 'тат', 'око', 'тик', 'рок', 'орт', 'бат', 'кат', 'тон', 'вир', 'нок', 'ток', 'ант', 'вар', 'обр', 'нтв', 'бит', 'ива', 'рот', 'бот', 'рев', 'кон', 'он', 'ер', 'быт', 'раб', 'три', 'нет', 'ир', 'боа', 'нар', 'еры', 'кин', 'тор', 'бар', 'кен', 'век', 'та', 'кар', 'кеб', 'она', 'бон', 'ро', 'ни', 'инк', 'ева', 'ера', 'ре', 'нит', 'бра', 'тот', 'тек', 'ат', 'бок'}


In [ ]:
s2 =  "объектно-ориентированный"
print(s2[:6])
print(s2[4]+s2[0]+s2[5])


объект
кот


# Задание 3

Строковый метод isdigit() проверяет, состоит ли строка только из цифр. Напишите программу, которая запрашивает с ввода целые числа и выводит их сумму. В случае некорректного ввода программа не должна завершаться с ошибкой, а должна продолжать работу, удаляя из введённой строки все символы кроме цифр. При отсутствии цифр запрс пользователю повторяется.

Обработчик исключений try-except использовать нельзя.

In [ ]:
sum = 0
while(sum == 0):
  #s = input("Input integer: ")
  s = '454555rxt55'
  for i in s:
    if i.isdigit() == True:
      sum = sum + int(i)
    else:
      s = s.replace(i, '')

print('sum = ', sum)
print('s = ', s)


sum =  38
s =  45455555


# Задание 4

Создайте словарь, где ключами являются числа, а значениями – строки. Примените к нему метод items(), полученный объект dict_items передайте в написанную вами функцию, которая создает и возвращает новый словарь, "обратный" исходному, т. е. ключами являются строки, а значениями – числа.

где строка обозначает ряд, столбец - место (0 - свободно, 1 - занято).

Напишите программу, которая позволит пользователю увидеть количество свободных мест, общее число мест в зале, число свободных мест в зале и в каждом ряду, а также, введя номер ряда и места, получить информацию - свободно оно или нет.

In [ ]:
def reverse_d(d):
  d_rev = {}
  for i in d:
    d_rev.update({i[1]: i[0]})
  return d_rev

d = {
     0 : 'Hello',
     1 : ',',
     2 : 'I,m',
     3 : 'Helen',
     4 : '!',
}.items()

d_rev = reverse_d(d).items()

print(d)
print(d_rev)

dict_items([(0, 'Hello'), (1, ','), (2, 'I,m'), (3, 'Helen'), (4, '!')])
dict_items([('Hello', 0), (',', 1), ('I,m', 2), ('Helen', 3), ('!', 4)])


In [ ]:
d = {
     ('a', 1) : 0,
     ('a', 2) : 1,
     ('a', 3) : 1,
     ('a', 4) : 1,
     ('b', 1) : 0,
     ('b', 2) : 1,
     ('b', 3) : 1,
     ('b', 4) : 0
}

def total_seats(d):
  return len(d.keys())

def free_seats(d):
  d_free = {}
  for i in d:
    if d.get(i) == 0:
      d_free.update({i: d.get(i)})
  return len(d_free)

def free_seats_row(d,row):
  d_free = {}
  for i in d:
    if i[0] == row:
       if d.get(i) == 0:
        d_free.update({i: d.get(i)})
  return len(d_free)

def seat_condition(row, seat):
  if d.get((row, seat)) == 0:
    return 'Свободно'
  else:
    return 'Занято'

print('Места: ', d.keys())
print('Количество свободных мест: ', free_seats(d))
print('Число мест в зале: ', total_seats(d))
print('Свободные места в ряду а:',  free_seats_row(d,'a'))
print('Свободные места в ряду b:',  free_seats_row(d,'b'))
print('Информация о месте а1: ' + seat_condition('a', 1) )
print('Информация о месте а2: ' + seat_condition('a', 2) )

Места:  dict_keys([('a', 1), ('a', 2), ('a', 3), ('a', 4), ('b', 1), ('b', 2), ('b', 3), ('b', 4)])
Количество свободных мест:  3
Число мест в зале:  8
Свободные места в ряду а: 1
Свободные места в ряду b: 2
Информация о месте а1: Свободно
Информация о месте а2: Занято


# Задание 5. (Снова в школу...)

Опишите структуру данных (базу данных) на основе словаря и интерфейс работы с ней (функцию). 

Создайте словарь school, и наполните его данными, которые бы отражали количество учащихся в разных классах (1а, 1б, 2б, 6а, 7в и т.п.). И функцию для внесения изменений в словарь в рамках следующего функционала: 
а) в одном из классов изменилось количество учащихся; 
б) в школе появился новый класс; 
с) в школе был расформирован (удален) класс, в связи с чем ученики были равномерно распределены по другим; 
d) выгрузка данных: общее количество учащихся в школе, общее колличество классав, распределение учеников по классам.

P.S. Дополнительно.

Подумайте как лучше всего хранить такую базу данных в файле. Попробуйте реализовать свою идею.

In [ ]:
class School():
  
  def __init__(self, db):
    self.db = db
  
  def get_db(self):
    return self.db

  def change_sum(self, class_, puple):
    self.db.update({class_: puple})

  def add_new_class(self, class_, puple):
    self.db.update({class_: puple})

  def remove_class_and_distribute_puple(self, class_):

    min = (0,0)
    min_val = 0
    
    for i in self.db:
      if i[0] == class_[0] and i[1]!= class_[1]:
        min = i
        min_val = self.db.get(i)
    
    if min == (0,0):
        return "ERROR you have no class to distribute_puple"
   
    while self.db.get(class_) != 0:
      for i in self.db:
        if i!= class_ and i[0] == class_[0] and self.db.get(i)<=min_val+1:
          min = i
          min_val = self.db.get(i)    
      self.db.update({min: min_val + 1})
      self.db.update({class_: self.db.get(class_)-1})  
    self.db.pop(class_)
  
  def count_puple(self):
    sum = 0
    for i in self.db:
      sum = sum + self.db.get(i)
    return sum
  
  def count_classes(self):
    return len(self.db.keys())

  def get_report(self):
    print('Количество классов: ', self.count_classes(), 'Количество учеников: ', self.count_puple(), 'Распределение учеников по классам', self.db.items())

school135 = School({
    (1, 'а'): 26,
    (1, 'б'): 25,
    (2, 'в'): 30,
    (2, 'б'): 28,
    (6, 'а'): 3,
    (6, 'г'): 3,
#   (6, 'б'): 39
})

print('БД школы: ')
print(school135.get_db())

school135.change_sum((1, 'а'),41)
print('а) в одном из классов изменилось количество учащихся: ')
print(school135.get_db() )

school135.add_new_class((6, 'б'), 39)
print('б) в школе появился новый класс:')
print(school135.get_db() )

school135.remove_class_and_distribute_puple((6, 'б'))
print('с) в школе был расформирован (удален) класс, в связи с чем ученики были равномерно распределены по другим:')
print(school135.get_db() )


print('d) выгрузка данных: общее количество учащихся в школе, общее колличество классов, распределение учеников по классам:')
print(school135.get_report())


БД школы: 
{(1, 'а'): 26, (1, 'б'): 25, (2, 'в'): 30, (2, 'б'): 28, (6, 'а'): 3, (6, 'г'): 3}
а) в одном из классов изменилось количество учащихся: 
{(1, 'а'): 41, (1, 'б'): 25, (2, 'в'): 30, (2, 'б'): 28, (6, 'а'): 3, (6, 'г'): 3}
б) в школе появился новый класс:
{(1, 'а'): 41, (1, 'б'): 25, (2, 'в'): 30, (2, 'б'): 28, (6, 'а'): 3, (6, 'г'): 3, (6, 'б'): 39}
с) в школе был расформирован (удален) класс, в связи с чем ученики были равномерно распределены по другим:
{(1, 'а'): 41, (1, 'б'): 25, (2, 'в'): 30, (2, 'б'): 28, (6, 'а'): 22, (6, 'г'): 23}
d) выгрузка данных: общее количество учащихся в школе, общее колличество классов, распределение учеников по классам:
Количество классов:  6 Количество учеников:  169 Распределение учеников по классам dict_items([((1, 'а'), 41), ((1, 'б'), 25), ((2, 'в'), 30), ((2, 'б'), 28), ((6, 'а'), 22), ((6, 'г'), 23)])
None


In [ ]:
#доп
#в формате "ФИО ученика|номер класса|буква класса"



# Домашнее задание (дополнительное):

# Задание. Реверс словаря.

Создайте словарь, где ключами являются цифры, а значениями – строки. Примените к нему метод items(), полученный объект dict_items передайте в функцию, которая создает и возвращает новый словарь, "обратный" исходному, приэтом ключами являются буквы составляющие строки, а значениями – числа составленные из цифр в порядке соответствующем .

In [ ]:
def reverse_func(d):
    new_d = {}
    for key, word in d.items():
        for w in word:
          new_d[w] = new_d.get(w, []) + [key]
    return new_d
        
d = {
    0: 'abc', 
    2: 'abdc', 
    3: 'abcdef'
    }
    
print(reverse_func(d))

{'a': [0, 2, 3], 'b': [0, 2, 3], 'c': [0, 2, 3], 'd': [2, 3], 'e': [3], 'f': [3]}


# Задание. Разрезание таблиц. 

Заполните квадратную таблицу порядка n по спирали по часовой стрелке начиная с левого верхнего угла. В напишите функцию принимающую данную таблицу в подходящем формате, найдите строку с наибольшим количеством нулей и столбец с максимальной суммой элементов. Разрежьте по этой строке и столбцу таблицу и верните из функции получившийся результат как отдельные таблицы, после чего выведете их на печать.

In [ ]:
import random
import numpy as np
n = 9
table =  np.empty([n, n])
arr = np.arange(0, n, 1)
i_arr = arr
j_arr = np.flip(i_arr)

In [ ]:
#ЗАПОЛНЕНИЕ
for i in i_arr:
  j_arr = np.flip(j_arr)
  for j in j_arr:
    #закомментить для проверки заполнения змейкой
    number = random.randint(0,n)
    table[i,j] = number
print('Исходная таблица с рандомными значениями: ')
print(table)

Исходная таблица с рандомными значениями: 
[[5. 1. 6. 7. 4. 9. 8. 3. 8.]
 [0. 7. 0. 4. 5. 2. 7. 2. 1.]
 [2. 1. 4. 9. 5. 5. 1. 2. 2.]
 [2. 9. 7. 7. 8. 8. 0. 0. 3.]
 [1. 8. 6. 5. 5. 3. 4. 1. 9.]
 [2. 4. 8. 8. 0. 2. 4. 2. 6.]
 [3. 3. 9. 4. 5. 2. 6. 9. 9.]
 [2. 2. 4. 5. 1. 3. 4. 0. 2.]
 [9. 4. 9. 6. 1. 7. 9. 7. 3.]]


In [ ]:
#САМАЯ БОЛЬШАЯ СУММА
def max_sum_col_func(table, arr):
  transpose_table = table.transpose()
  max_sum_col = 0
  max_sum = 0
  for i in arr:
    sum = 0
    for j in arr:
      sum = sum + transpose_table[i][j]
    if sum > max_sum:
      max_sum = sum
      max_sum_col = i
  return  max_sum_col
print('max_sum_col: ',max_sum_col_func(table, arr))

max_sum_col:  3


In [ ]:
#БОЛЬШЕ ВСЕГО 0
def max_zero_row_func(table, arr):
  max_zero_row = 0
  max_sum_zero = 0
  for row in arr:
    sum_zero = 0
    for j in arr:
      if table[row][j] == 0:
        sum_zero = sum_zero + 1
    if sum_zero > max_sum_zero:
      max_sum_zero = sum_zero
      max_zero_row = row
  return max_zero_row

print('max zero row: ', max_zero_row_func(table, arr))

max zero row:  1


In [ ]:
#РАЗРЕЗАНИЕ И ВЫВОД
row = max_zero_row_func(table, arr)
col = max_sum_col_func(table, arr)
part1 = []
part2 = []
part3 = []
part4 = []
for i in arr:
     if i < row:
        part1.append(table[i][0:col])
        part2.append(table[i][col:n])
     else:
        part3.append(table[i][0:col])
        part4.append(table[i][col:n])

print("original_table:")
print(table)
print('row: ', row)
print('col: ', col)   
print('part1:')
print(part1)
print('part2:')
print(part2)
print('part3:')
print(part3)
print('part4:')
print(part4)

original_table:
[[5. 1. 6. 7. 4. 9. 8. 3. 8.]
 [0. 7. 0. 4. 5. 2. 7. 2. 1.]
 [2. 1. 4. 9. 5. 5. 1. 2. 2.]
 [2. 9. 7. 7. 8. 8. 0. 0. 3.]
 [1. 8. 6. 5. 5. 3. 4. 1. 9.]
 [2. 4. 8. 8. 0. 2. 4. 2. 6.]
 [3. 3. 9. 4. 5. 2. 6. 9. 9.]
 [2. 2. 4. 5. 1. 3. 4. 0. 2.]
 [9. 4. 9. 6. 1. 7. 9. 7. 3.]]
row:  1
col:  3
part1:
[array([5., 1., 6.])]
part2:
[array([7., 4., 9., 8., 3., 8.])]
part3:
[array([0., 7., 0.]), array([2., 1., 4.]), array([2., 9., 7.]), array([1., 8., 6.]), array([2., 4., 8.]), array([3., 3., 9.]), array([2., 2., 4.]), array([9., 4., 9.])]
part4:
[array([4., 5., 2., 7., 2., 1.]), array([9., 5., 5., 1., 2., 2.]), array([7., 8., 8., 0., 0., 3.]), array([5., 5., 3., 4., 1., 9.]), array([8., 0., 2., 4., 2., 6.]), array([4., 5., 2., 6., 9., 9.]), array([5., 1., 3., 4., 0., 2.]), array([6., 1., 7., 9., 7., 3.])]


# Задание. Пары.

На вход программы поступает последовательность из N целых положительных чисел, все числа в последовательности различны. Рассматриваются все пары различных элементов последовательности (элементы пары не обязаны стоять в последовательности рядом, порядок элементов в паре не важен). Необходимо определить количество пар, для которых произведение элементов делится на 26.
Описание входных и выходных данных.

В первой строке входных данных задаётся количество чисел N (1 ≤ N ≤ 1000). В каждой из последующих N строк записано одно целое положительное число, не превышающее 10 000.

В качестве результата программа должна напечатать одно число: количество пар, в которых произведение элементов кратно 26.

Пример входных данных: 4 2 6 13 39

Пример выходных данных: 4

Из четырёх заданных чисел можно составить 6 попарных произведений:

2·6 = 12 

2·13 = 26 

2·39 = 78 

6·13 = 78

6·39 = 234 

13·39 = 507

Из них на 26 делятся 4 произведения:

2·13=26

2·39=78

6·13=78

6·39=234

Требуется написать эффективную по времени и по памяти программу для решения описанной задачи.

(Программа считается эффективной по времени, если при увеличении количества исходных чисел N в k раз время работы программы увеличивается не более чем в k раз. Программа считается эффективной по памяти, если память, необходимая для хранения всех переменных программы, не превышает 1 Кбайт и не меняется с ростом N.)

In [ ]:
N = 5
numbers = [2, 6, 13, 39, 26]
del26 = [2, 13, 26]
sum_2 = 0
sum_13 = 0
sum_26 = 0
for i in numbers:
  if i%26 == 0:
    sum_26 += 1
  elif i%13 == 0:
    sum_13 += 1
  elif i%2 == 0:
    sum_2 += 1

sum_pairs = sum_26*N - sum_26 + sum_13*sum_2

print(sum_pairs) 


8
